'use strict';
(function () {
  const DATA = window.ChemistryData || {};
  const n = (p, key, fallback) => Number.isFinite(Number(p[key])) ? Number(p[key]) : fallback;
  const clip = (x) => Math.max(0, Math.min(100, x));
  const formula = (name, text, given, calc, result, unit) => ({ name, formula: text, given, calc, result, unit });

function calculate(kind, p) {
    let value = 0, result = '', unit = '', text = '', given = '', calc = '', values = [], explain = '', graph = null;
    const ca = n(p, 'ca', 0), mg = n(p, 'mg', 0);
    if (kind === 'hardness') { value = ca + mg; result = value.toFixed(1); unit = 'mg/L as CaCO₃'; text = 'H = Ca²⁺ + Mg²⁺'; given = ca + ' + ' + mg; calc = 'H = ' + result; values = [['Total hardness', result + ' mg/L'], ['Temporary hardness', (value * .42).toFixed(1) + ' mg/L'], ['Permanent hardness', (value * .58).toFixed(1) + ' mg/L']]; explain = 'Calcium and magnesium are converted to a common CaCO₃ equivalent.'; }
    else if (kind === 'edta') { const v = n(p, 'edtaVolume', 0), m = n(p, 'edtaMolarity', 0), sv = n(p, 'sampleVolume', 1); value = v * m * 100000 / sv; result = value.toFixed(1); unit = 'mg/L as CaCO₃'; text = 'H = V_EDTA × M_EDTA × 100000 / V_sample'; given = v + ' mL, ' + m + ' M, ' + sv + ' mL'; calc = result; values = [['EDTA titre', v.toFixed(1) + ' mL'], ['Endpoint pH', n(p, 'pH', 10).toFixed(1)], ['Hardness', result + ' mg/L']]; explain = 'At pH 10, EDTA binds Ca²⁺ and Mg²⁺ in a 1:1 complex.'; }
    else if (kind === 'limeSoda') { const raw = n(p, 'hardness', 0); const rem = Math.max(0, raw - n(p, 'limeDose', 0) * .72 - n(p, 'sodaDose', 0) * .66); value = rem; result = rem.toFixed(1); unit = 'mg/L residual'; text = 'Residual = raw − 0.72 lime − 0.66 soda'; given = raw + ' mg/L'; calc = result; values = [['Raw hardness', raw.toFixed(0) + ' mg/L'], ['Precipitated solids', (raw - rem).toFixed(1) + ' mg/L'], ['Residual hardness', result + ' mg/L']]; explain = 'Lime precipitates carbonate hardness and soda ash removes non-carbonate calcium hardness.'; }
    else if (kind === 'zeolite') { const h = n(p, 'hardness', 0), cap = n(p, 'capacity', 1), reg = n(p, 'regeneration', 0); value = Math.min(h, cap * .5 * (.5 + reg / 200)); result = value.toFixed(1); unit = 'mg/L removed'; text = 'Exchange = capacity × regeneration factor'; given = h + ' mg/L, ' + reg + '%'; calc = result; values = [['Bed loading', clip(h / cap * 100).toFixed(0) + '%'], ['Exchange removed', result + ' mg/L'], ['Regeneration', reg.toFixed(0) + '%']]; explain = 'Sodium zeolite exchanges Na⁺ for Ca²⁺ and Mg²⁺; brine restores capacity.'; }
    else if (kind === 'ionExchange') { const t = n(p, 'tds', 0), c = n(p, 'cationRemoval', 0), a = n(p, 'anionRemoval', 0); value = t * (1 - c / 100) * (1 - a / 100); result = value.toFixed(1); unit = 'mg/L TDS'; text = 'TDSout = TDSin(1 − c)(1 − a)'; given = t + ' mg/L'; calc = result; values = [['Cation removal', c.toFixed(0) + '%'], ['Anion removal', a.toFixed(0) + '%'], ['Product TDS', result + ' mg/L']]; explain = 'Cation resin releases H⁺ and anion resin releases OH⁻, forming water.'; }
    else if (kind === 'ro') { const salt = n(p, 'salt', 0), rej = n(p, 'membrane', 0), pressure = n(p, 'pressure', 0); value = salt * (1 - rej / 100); result = value.toFixed(1); unit = 'mg/L permeate'; text = 'Saltout = Saltin(1 − rejection)'; given = salt + ' mg/L, ' + rej + '%'; calc = result; values = [['Pressure', pressure.toFixed(0) + ' bar'], ['Rejection', rej.toFixed(0) + '%'], ['Permeate salinity', result + ' mg/L']]; explain = 'Pressure drives water through a semipermeable membrane while salt is rejected.'; }
    else if (kind === 'municipal' || kind === 'filtration') { const turb = n(p, 'turbidity', 0), dose = n(p, kind === 'municipal' ? 'alum' : 'depth', 0), flow = n(p, kind === 'municipal' ? 'chlorine' : 'flow', 1); value = turb * Math.max(.03, 1 - dose / (kind === 'municipal' ? 100 : 150)) + flow * .08; result = value.toFixed(1); unit = 'NTU'; text = 'Outlet turbidity = inlet × treatment factor'; given = turb + ' NTU'; calc = result; values = [['Inlet turbidity', turb.toFixed(1) + ' NTU'], ['Treatment factor', (100 - clip(dose)).toFixed(1) + '%'], ['Outlet turbidity', result + ' NTU']]; explain = kind === 'municipal' ? 'Coagulation, sedimentation, filtration and disinfection form the municipal treatment train.' : 'Sand depth traps particles while flow rate changes contact time and head loss.'; }
    else if (kind === 'sedimentation') { const size = n(p, 'particle', 1), time = n(p, 'settling', 1), dose = n(p, 'coagulant', 0); value = clip(100 * (1 - Math.exp(-time * (size / 80 + dose / 300)))); result = value.toFixed(1); unit = '% removal'; text = 'η = 100(1 − e^(−t(d/80 + dose/300)))'; given = size + ' µm, ' + time + ' min'; calc = result; values = [['Particle size', size.toFixed(0) + ' µm'], ['Coagulant dose', dose.toFixed(0) + ' mg/L'], ['Settled solids', result + '%']]; explain = 'Coagulant creates larger flocs whose settling velocity is higher.'; }
    else if (kind === 'disinfection') { const dose = n(p, 'dose', 0), time = n(p, 'contact', 1), load = n(p, 'microbes', 0); value = clip(100 * (1 - Math.exp(-dose * time / 45))); result = value.toFixed(1); unit = '% reduction'; text = 'Kill = 100(1 − e^(−dose×time/45))'; given = dose + ' mg/L × ' + time + ' min'; calc = result; values = [['Dose-time product', (dose * time).toFixed(1) + ' mg·min/L'], ['Microbial reduction', result + '%'], ['Remaining load', (load * (1 - value / 100)).toFixed(1) + '%']]; explain = 'Disinfection effectiveness is controlled by the dose-time product.'; }
    else if (kind === 'electrodialysis') { const v = n(p, 'voltage', 0), pairs = n(p, 'pairs', 1), salt = n(p, 'salt', 0); const removal = clip(v * pairs * .22); value = salt * (1 - removal / 100); result = value.toFixed(1); unit = 'mg/L product salt'; text = 'Removal = 0.22 × voltage × membrane pairs'; given = v + ' V, ' + pairs + ' pairs'; calc = removal.toFixed(1) + '%'; values = [['Ion migration', removal.toFixed(1) + '%'], ['Membrane pairs', pairs.toFixed(0)], ['Product salt', result + ' mg/L']]; explain = 'An electric field moves cations and anions through alternating ion-selective membranes.'; }
    else if (kind === 'cell') { const cathode = typeof p.cathode === 'string' && DATA.electrodes[p.cathode] ? DATA.electrodes[p.cathode] : { symbol: 'cathode', potential: n(p, 'cathode', 0) }; const anode = typeof p.anode === 'string' && DATA.electrodes[p.anode] ? DATA.electrodes[p.anode] : { symbol: 'anode', potential: n(p, 'anode', 0) }; const cath = cathode.potential, an = anode.potential; value = cath - an; result = value.toFixed(2); unit = 'V'; text = 'E°cell = E°cathode − E°anode'; given = cathode.symbol + ' (' + cath.toFixed(2) + ') − ' + anode.symbol + ' (' + an.toFixed(2) + ')'; calc = result; values = [['Cathode', cathode.symbol + ' · ' + cath.toFixed(2) + ' V'], ['Anode', anode.symbol + ' · ' + an.toFixed(2) + ' V'], ['Electron flow', anode.symbol + ' → ' + cathode.symbol], ['Spontaneous', value > 0 ? 'Yes' : 'No']]; explain = 'The electrode database supplies standard reduction potentials; the more positive electrode is the cathode.'; }
    else if (kind === 'calomel') { const a = n(p, 'chloride', 1), t = n(p, 'temperature', 25), e0 = n(p, 'reference', .241); value = e0 - .0591 * Math.log(a) / 2 + (t - 25) * .0002; result = value.toFixed(3); unit = 'V vs SHE'; text = 'E = E° − (0.0591/2)log a(Cl⁻)'; given = a.toFixed(2) + ' M'; calc = result; values = [['Reference E°', e0.toFixed(3) + ' V'], ['Chloride activity', a.toFixed(2) + ' M'], ['Electrode output', result + ' V']]; explain = 'The Hg/Hg₂Cl₂/KCl electrode provides a stable chloride-controlled reference potential.'; }
    else if (kind === 'leadAcid') { const soc = n(p, 'soc', 0), current = n(p, 'current', 0), density = n(p, 'acidDensity', 1.2); value = 1.95 + soc * .002 - Math.abs(current) * .006; result = value.toFixed(2); unit = 'V/cell'; text = 'V ≈ 1.95 + 0.002SOC − 0.006|I|'; given = soc + '% SOC'; calc = result; values = [['State of charge', soc.toFixed(0) + '%'], ['Electrolyte density', density.toFixed(3) + ' g/mL'], ['Cell voltage', result + ' V']]; explain = 'Discharge consumes active lead compounds and sulfuric acid; charging reverses the reaction.'; }
    else if (kind === 'lithium') { const soc = n(p, 'soc', 0), current = n(p, 'current', 0), resistance = n(p, 'resistance', .1); const ocv = 3 + soc * .012; value = ocv - current * resistance; result = value.toFixed(2); unit = 'V'; text = 'V = OCV(SOC) − I·R'; given = ocv.toFixed(2) + ' V − ' + current + '×' + resistance; calc = result; values = [['Open-circuit voltage', ocv.toFixed(2) + ' V'], ['IR drop', (current * resistance).toFixed(2) + ' V'], ['Terminal voltage', result + ' V']]; explain = 'Lithium ions shuttle between host structures while electrons travel through the load.'; }
    else if (kind === 'fuelCell') { const h = n(p, 'hydrogen', 0), o = n(p, 'oxygen', 0), t = n(p, 'temperature', 25); value = clip(Math.min(h, o) * .82 + Math.max(0, t - 300) * .015); result = value.toFixed(1); unit = '% efficiency'; text = 'η ≈ 0.82·min(H₂,O₂) + temperature benefit'; given = h + '% H₂, ' + o + '% O₂'; calc = result; values = [['Hydrogen utilisation', h.toFixed(0) + '%'], ['Water product', (Math.min(h, o) * .5).toFixed(1) + ' units'], ['Electrical efficiency', result + '%']]; explain = 'Hydrogen is oxidised at the anode; protons cross the electrolyte and electrons power the load.'; }
    else if (kind === 'solar') { const irr = n(p, 'irradiance', 0), t = n(p, 'temperature', 25), load = n(p, 'load', 1); const current = irr * .004, voltage = Math.max(0, .72 - (t - 25) * .002); value = Math.min(current * voltage, voltage * voltage / Math.max(load, .1)); result = value.toFixed(2); unit = 'W'; text = 'P = V × I'; given = irr + ' W/m², ' + t + ' °C'; calc = result; graph = []; for (let i = 1; i <= 20; i++) { const resistance = i / 2; graph.push([resistance, Math.min(current * voltage, voltage * voltage / resistance)]); } values = [['Photocurrent', current.toFixed(2) + ' A'], ['Cell voltage', voltage.toFixed(2) + ' V'], ['Power', result + ' W']]; explain = 'Photons create electron-hole pairs; the load selects the operating point on the I–V curve.'; }
    else if (kind === 'corrosion') { const t = n(p, 'temperature', 25), o = n(p, 'oxygen', 50), time = n(p, 'time', 20); value = clip(t / 120 * o / 100 * time / 40 * 100); result = value.toFixed(1); unit = 'relative rate'; text = 'Rate ∝ temperature × oxygen × exposure'; given = t + ' °C, ' + o + '% O₂, ' + time + ' h'; calc = result; values = [['Anodic activity', (value * .62).toFixed(1)], ['Cathodic activity', (value * .38).toFixed(1)], ['Corrosion rate', result + '%']]; explain = 'Anodic metal dissolution couples to cathodic reduction; environment and geometry control the rate.'; }
    else if (kind === 'protection') { const current = n(p, 'current', 0), area = n(p, 'area', 1), potential = n(p, 'potential', -.85); value = clip(current * 14 + area * .3); result = value.toFixed(1); unit = '% protection'; text = 'Protection = 14I + 0.3 area'; given = current + ' A, ' + area + ' cm²'; calc = result; values = [['Structure potential', potential.toFixed(2) + ' V'], ['Protected area', area.toFixed(0) + ' cm²'], ['Protection index', result + '%']]; explain = 'Sacrificial anodes dissolve preferentially; impressed current supplies electrons to keep the structure cathodic.'; }
    else if (kind === 'plating') { const i = n(p, 'current', 0), time = n(p, 'time', 0), area = n(p, 'area', 1); value = i * time * .00035 / area; result = value.toFixed(3); unit = 'mm coating'; text = 'Thickness ∝ I·t/A'; given = i + ' A × ' + time + ' min / ' + area + ' cm²'; calc = result; values = [['Current density', (i / area).toFixed(3) + ' A/cm²'], ['Deposition time', time.toFixed(0) + ' min'], ['Coating thickness', result + ' mm']]; explain = 'Metal ions are reduced at the cathode; Faraday’s law links deposited thickness to current and time.'; }
    else if (kind === 'alloy') { const cu = n(p, 'copper', 0), zn = n(p, 'zinc', 0), ni = n(p, 'nickel', 0), total = Math.max(1, cu + zn + ni); value = (cu * .5 + zn * .8 + ni * 1.1) / total * 100; result = value.toFixed(1); unit = 'property index'; text = 'Property = weighted composition'; given = cu + '% Cu, ' + zn + '% Zn, ' + ni + '% Ni'; calc = result; values = [['Copper', (cu / total * 100).toFixed(1) + '%'], ['Zinc', (zn / total * 100).toFixed(1) + '%'], ['Strength index', result]]; explain = 'Alloy properties depend on composition, solid-solution effects and phases after processing.'; }
    else if (kind === 'heatTreatment') { const t = n(p, 'temperature', 0), soak = n(p, 'soak', 0), cool = n(p, 'cooling', 1); value = clip(20 + t * .06 + soak * .18 - cool * .12); result = value.toFixed(1); unit = 'hardness index'; text = 'H = 20 + 0.06T + 0.18t − 0.12r'; given = t + ' °C, ' + soak + ' min'; calc = result; values = [['Heat stage', t.toFixed(0) + ' °C'], ['Soak', soak.toFixed(0) + ' min'], ['Hardness index', result]]; explain = 'Heating, diffusion, soaking and cooling rate determine the final microstructure.'; }
    else if (kind === 'proximate') { const mass = n(p, 'mass', 1), moisture = n(p, 'moisture', 0), ash = n(p, 'ash', 0); value = Math.max(0, 100 - moisture - ash - 25); result = value.toFixed(1); unit = '% fixed carbon'; text = 'FC = 100 − moisture − volatile matter − ash'; given = moisture + '% moisture, ' + ash + '% ash'; calc = result; values = [['Moisture', moisture.toFixed(1) + '%'], ['Ash', ash.toFixed(1) + '%'], ['Fixed carbon', result + '%'], ['Sample', mass.toFixed(1) + ' g']]; explain = 'Controlled heating separates moisture, volatile matter, ash and remaining fixed carbon.'; }
    else if (kind === 'coal') { const mass = n(p, 'mass', 1), carbon = n(p, 'carbon', 0), sulfur = n(p, 'sulfur', 0); value = carbon * .34 - sulfur * .7; result = value.toFixed(1); unit = 'MJ/kg index'; text = 'CV ≈ 0.34 carbon − 0.70 sulfur'; given = carbon + '% carbon, ' + sulfur + '% sulfur'; calc = result; values = [['Carbon', carbon.toFixed(1) + '%'], ['Sulfur', sulfur.toFixed(1) + '%'], ['Heating value', result + ' MJ/kg'], ['Sample', mass.toFixed(1) + ' g']]; explain = 'Ultimate analysis relates composition to heating value and emissions.'; }
    else if (kind === 'bergius') { const pressure = n(p, 'pressure', 0), t = n(p, 'temperature', 0), h = n(p, 'hydrogen', 0); value = clip(pressure * .08 + (t - 250) * .08 + h * .25); result = value.toFixed(1); unit = '% oil yield'; text = 'Yield ∝ pressure + temperature + hydrogen'; given = pressure + ' bar, ' + t + ' °C'; calc = result; values = [['Pressure', pressure.toFixed(0) + ' bar'], ['Hydrogen ratio', h.toFixed(0) + '%'], ['Synthetic petrol', result + '%']]; explain = 'Powdered coal is hydrogenated with catalyst under high pressure and temperature to liquid hydrocarbons.'; }
    else if (kind === 'octane') { const iso = n(p, 'isoOctane', 0), hep = n(p, 'heptane', 0); value = 100 * iso / Math.max(1, iso + hep); result = value.toFixed(1); unit = 'octane number'; text = 'ON = 100 × iso-octane / total reference blend'; given = iso + '% iso-octane, ' + hep + '% n-heptane'; calc = result; values = [['Iso-octane', iso.toFixed(0) + '%'], ['n-Heptane', hep.toFixed(0) + '%'], ['Octane number', result]]; explain = 'Octane number compares petrol knock resistance with iso-octane and n-heptane standards.'; }
    else if (kind === 'cetane') { const c = n(p, 'cetane', 0), delay = n(p, 'ignitionDelay', 1), t = n(p, 'temperature', 0); value = clip(c * .9 + t * .02 - delay * .4); result = value.toFixed(1); unit = 'quality index'; text = 'Quality ∝ cetane fraction − ignition delay'; given = c + '% cetane, ' + delay + ' ms'; calc = result; values = [['Ignition delay', delay.toFixed(1) + ' ms'], ['Injection temperature', t.toFixed(0) + ' °C'], ['Diesel quality', result]]; explain = 'Higher cetane number gives a shorter diesel ignition delay.'; }
    else if (kind === 'knocking') { const cr = n(p, 'compression', 1), oct = n(p, 'octane', 0), t = n(p, 'temperature', 0); value = clip(cr * 5 + t * .08 - oct * .55); result = value.toFixed(1); unit = '% knock risk'; text = 'Risk = 5CR + 0.08T − 0.55 octane'; given = cr + ':1, ' + t + ' K, ON ' + oct; calc = result; values = [['End-gas temperature', t.toFixed(0) + ' K'], ['Fuel octane', oct.toFixed(0)], ['Knock risk', result + '%']]; explain = 'Auto-ignition of the end gas creates pressure waves; higher octane suppresses knock.'; }
    else if (kind === 'antiKnock') { const base = n(p, 'baseOctane', 0), add = n(p, 'additive', 0), cr = n(p, 'compression', 1); const oct = Math.min(120, base + add * 1.8); value = clip(cr * 5 - oct * .55); result = oct.toFixed(1); unit = 'blended octane'; text = 'ONblend = base ON + 1.8 additive'; given = base + ' ON + ' + add + '%'; calc = result; values = [['Blended octane', result], ['Compression ratio', cr.toFixed(1) + ':1'], ['Remaining knock risk', value.toFixed(1) + '%']]; explain = 'Anti-knock agents raise resistance to auto-ignition and allow higher compression.'; }
    else if (kind === 'cngLpg') { const ch4 = n(p, 'methane', 0), prop = n(p, 'propane', 0), pressure = n(p, 'pressure', 0); value = ch4 * .055 + prop * .095; result = value.toFixed(2); unit = 'relative energy index'; text = 'Energy = 0.055 CH₄ + 0.095 C₃H₈'; given = ch4 + '% methane, ' + prop + '% propane'; calc = result; values = [['CNG methane', ch4.toFixed(0) + '%'], ['LPG propane', prop.toFixed(0) + '%'], ['Storage pressure', pressure.toFixed(0) + ' bar'], ['Energy index', result]]; explain = 'CNG is mainly methane at high pressure; LPG contains propane/butane as a liquefied gas.'; }
    else if (kind === 'calorific') { const mass = n(p, 'mass', 1), heat = n(p, 'heat', 1), water = n(p, 'water', 1); value = heat * water / mass; result = value.toFixed(1); unit = 'kJ/g'; text = 'CV = heat × water equivalent / mass'; given = heat + ' kJ, ' + water + ' kJ/K, ' + mass + ' g'; calc = result; values = [['Fuel mass', mass.toFixed(2) + ' g'], ['Heat released', heat.toFixed(1) + ' kJ'], ['Calorific value', result + ' kJ/g']]; explain = 'Calorific value is heat released by complete combustion per unit mass.'; }
    else if (kind === 'bomb') { const mass = n(p, 'mass', 1), dt = n(p, 'deltaT', 1), corr = n(p, 'corrections', 0); value = (dt * 10 - corr) / mass; result = value.toFixed(1); unit = 'kJ/g'; text = 'HCV = (WΔT − corrections) / mass'; given = dt + ' °C rise, ' + mass + ' g'; calc = result; values = [['Water rise', dt.toFixed(1) + ' °C'], ['Corrections', corr.toFixed(1) + ' kJ'], ['Higher CV', result + ' kJ/g']]; explain = 'A weighed sample burns in a sealed oxygen bomb; water temperature rise gives HCV.'; }
    else if (kind === 'orsat') { const co2 = n(p, 'co2', 0), o2 = n(p, 'oxygenGas', 0), co = n(p, 'co', 0); value = Math.max(0, 100 - co2 - o2 - co); result = value.toFixed(1); unit = '% nitrogen'; text = 'N₂ = 100 − CO₂ − O₂ − CO'; given = co2 + '% + ' + o2 + '% + ' + co + '% absorbed'; calc = result; values = [['CO₂', co2.toFixed(1) + '%'], ['O₂', o2.toFixed(1) + '%'], ['CO', co.toFixed(1) + '%'], ['N₂ by difference', result + '%']]; explain = 'Orsat reagents absorb CO₂, O₂ and CO successively; the remaining gas is nitrogen.'; }
    else if (kind === 'catalyst') { const co = n(p, 'co', 0), hc = n(p, 'hc', 0), nox = n(p, 'nox', 0); value = clip(70 + (co + hc + nox) * 2); result = value.toFixed(1); unit = '% conversion'; text = 'CO/HC/NOx → CO₂/H₂O/N₂'; given = co + '% CO, ' + hc + '% HC, ' + nox + '% NOx'; calc = result; values = [['CO converted', (co * value / 100).toFixed(2) + '%'], ['HC converted', (hc * value / 100).toFixed(2) + '%'], ['NOx converted', (nox * value / 100).toFixed(2) + '%']]; explain = 'A three-way catalyst oxidises CO and hydrocarbons and reduces NOx near stoichiometric mixture.'; }
    else if (kind === 'scr') { const nox = n(p, 'nox', 0), red = n(p, 'reductant', 0), t = n(p, 'temperature', 0); const conv = clip(red * .75 * Math.max(0, 1 - Math.abs(t - 350) / 500)); value = nox * (1 - conv / 100); result = value.toFixed(0); unit = 'ppm NOx outlet'; text = 'NOx + NH₃ → N₂ + H₂O'; given = nox + ' ppm, ' + red + '% reductant'; calc = conv.toFixed(1) + '% conversion'; values = [['Conversion', conv.toFixed(1) + '%'], ['Outlet NOx', result + ' ppm'], ['Temperature window', t >= 250 && t <= 450 ? 'Active' : 'Limited']]; explain = 'SCR injects ammonia or urea to reduce NOx selectively to nitrogen and water.'; }
    else if (kind === 'polymerization') { const mon = n(p, 'monomers', 1), conv = n(p, 'conversion', 0), init = n(p, 'initiator', 0); value = Math.max(1, Math.round(mon * conv / 100 * (1 + init / 100))); result = String(value); unit = 'repeat units'; text = 'DP ≈ monomers × conversion × initiator factor'; given = mon + ' monomers, ' + conv + '% conversion'; calc = result; values = [['Monomers joined', result], ['Conversion', conv.toFixed(0) + '%'], ['Initiator', init.toFixed(1) + '%']]; explain = 'Polymerization links monomers into chains; conversion and initiation control chain length.'; }
    else if (kind === 'dp') { const mw = n(p, 'polymerMass', 1), rw = n(p, 'repeatMass', 1), pd = n(p, 'polydispersity', 1); value = mw / rw; result = value.toFixed(0); unit = 'repeat units'; text = 'DP = Mpolymer / Mrepeat'; given = mw + ' / ' + rw; calc = result; values = [['Number-average DP', result], ['Polydispersity', pd.toFixed(2)], ['Chain class', value > 500 ? 'High polymer' : 'Oligomer']]; explain = 'Degree of polymerization is the average number of repeat units in one chain.'; }
    else if (kind === 'classification') { const linear = n(p, 'linear', 0), cross = n(p, 'crosslink', 0); value = cross > 45 ? 3 : linear > 55 ? 1 : 2; result = value === 1 ? 'Thermoplastic' : value === 2 ? 'Elastomeric' : 'Thermosetting'; unit = 'dominant class'; text = 'Structure → processing behaviour'; given = linear + '% linear, ' + cross + '% cross-links'; calc = result; values = [['Linear chains', linear.toFixed(0) + '%'], ['Cross-links', cross.toFixed(0) + '%'], ['Class', result]]; explain = 'Chain architecture controls softening, permanent networks and elastic behaviour.'; }
    else if (kind === 'thermo') { const t = n(p, 'temperature', 0), cross = n(p, 'crosslink', 0), cycles = n(p, 'cycles', 1); value = cross < 35 ? clip(100 - cross * 1.2) : 0; result = value.toFixed(1); unit = '% remeltability'; text = 'Remeltability = 100 − 1.2 × crosslink'; given = t + ' °C, ' + cross + '% cross-links'; calc = result; values = [['Processing temperature', t.toFixed(0) + ' °C'], ['Heating cycles', cycles.toFixed(0)], ['Remeltability', result + '%']]; explain = 'Thermoplastics soften repeatedly; thermosets form permanent cross-links and do not remelt.'; }
    else if (kind === 'tg') { const t = n(p, 'temperature', 0), tg = n(p, 'tg', 0), pl = n(p, 'plasticizer', 0); value = clip(50 + (t - tg + pl * 1.5) * 1.2); result = value.toFixed(1); unit = '% mobility'; text = 'Mobility = f(T − Tg + plasticizer)'; given = t + ' °C, Tg ' + tg + ' °C'; calc = result; values = [['T − Tg', (t - tg).toFixed(1) + ' °C'], ['Plasticizer shift', (pl * 1.5).toFixed(1) + ' °C'], ['State', t < tg ? 'Glassy' : 'Rubbery']]; explain = 'Below Tg segments are frozen; above Tg cooperative segment motion makes the polymer rubbery.'; }
    else if (kind === 'abs') { const a = n(p, 'acrylonitrile', 0), b = n(p, 'butadiene', 0), s = n(p, 'styrene', 0); value = (a * .9 + b * .7 + s * .8) / Math.max(1, a + b + s) * 100; result = value.toFixed(1); unit = 'toughness index'; text = 'ABS index = weighted monomer composition'; given = a + '% + ' + b + '% + ' + s + '%'; calc = result; values = [['Acrylonitrile', a.toFixed(0) + '%'], ['Butadiene', b.toFixed(0) + '%'], ['Styrene', s.toFixed(0) + '%'], ['Toughness index', result]]; explain = 'ABS combines chemical resistance, impact toughness and processability from its three monomers.'; }
    else if (kind === 'pvc' || kind === 'ptfe') { const units = n(p, kind === 'pvc' ? 'vinylChloride' : 'tetrafluoroethylene', 1), conv = n(p, 'conversion', 0); value = Math.max(1, Math.round(units * conv / 100)); result = String(value); unit = 'repeat units'; text = 'DP = feed units × conversion'; given = units + ' units, ' + conv + '%'; calc = result; values = [['Repeat units', result], ['Conversion', conv.toFixed(0) + '%'], ['Polymer', kind === 'pvc' ? 'PVC' : 'PTFE']]; explain = kind === 'pvc' ? 'PVC forms from vinyl chloride; plasticizer adjusts flexibility.' : 'PTFE forms from TFE; fluorination gives chemical resistance and low friction.'; }
    else if (kind === 'bakelite') { const ph = n(p, 'phenol', 0), fo = n(p, 'formaldehyde', 0), cross = n(p, 'crosslink', 0); value = clip(Math.min(ph, fo) * .8 + cross * .4); result = value.toFixed(1); unit = '% cure'; text = 'Cure = limiting reactant × 0.8 + crosslink'; given = ph + '% phenol, ' + fo + '% formaldehyde'; calc = result; values = [['Phenol', ph.toFixed(0) + '%'], ['Formaldehyde', fo.toFixed(0) + '%'], ['Network cure', result + '%']]; explain = 'Phenol and formaldehyde condense into a permanently cross-linked phenolic resin.'; }
    else if (kind === 'injection' || kind === 'extrusion' || kind === 'compression') { const t = n(p, 'temperature', 150), force = n(p, kind === 'extrusion' ? 'speed' : 'pressure', 1), time = n(p, kind === 'injection' ? 'cooling' : 'time', 1); value = clip(t * .18 + force * .32 + time * .6); result = value.toFixed(1); unit = '% process quality'; text = 'Quality = f(temperature, force/speed, time)'; given = t + ' °C, ' + force + ', ' + time; calc = result; values = [['Heat stage', t.toFixed(0) + ' °C'], ['Force / speed', force.toFixed(1)], ['Product quality', result + '%']]; explain = kind === 'injection' ? 'Pellets melt, fill a mould under pressure and cool before ejection.' : kind === 'extrusion' ? 'A screw melts polymer and pushes it through a die as a continuous profile.' : 'Heat and pressure consolidate polymer inside a closed mould.'; }
    else if (kind === 'conducting') { const d = n(p, 'doping', 0), chain = n(p, 'chainLength', 1), t = n(p, 'temperature', 0); value = d * chain * .42 * (1 + t / 400); result = value.toFixed(2); unit = 'relative conductivity'; text = 'σ ∝ doping × conjugated chain × temperature'; given = d + '% × ' + chain + ' units'; calc = result; values = [['Doping', d.toFixed(1) + '%'], ['Conjugated chain', chain.toFixed(0) + ' units'], ['Conductivity', result]]; explain = 'Delocalised π-electrons carry charge along the conjugated backbone; doping creates carriers.'; }
    else if (kind === 'frp') { const fibre = n(p, 'fiber', 0), angle = n(p, 'orientation', 0), load = n(p, 'load', 0); const eff = fibre * Math.cos(angle * Math.PI / 180) ** 2; value = load / Math.max(1, 100 - eff); result = value.toFixed(2); unit = 'load index'; text = 'Reinforcement ∝ fibre fraction × cos²θ'; given = fibre + '% fibre at ' + angle + '°'; calc = result; values = [['Fibre fraction', fibre.toFixed(0) + '%'], ['Orientation efficiency', (Math.cos(angle * Math.PI / 180) ** 2 * 100).toFixed(1) + '%'], ['Load index', result]]; explain = 'Fibres carry load along their orientation while the matrix transfers stress.'; }
    else if (kind === 'potentiometric') { const v = n(p, 'titrant', 0), e = n(p, 'potential', 0), slope = n(p, 'slope', 0); value = v; result = v.toFixed(1); unit = 'mL endpoint'; text = 'Endpoint = maximum ΔE/ΔV'; given = v + ' mL, ' + e + ' mV'; calc = slope.toFixed(1) + ' mV/mL'; graph = []; for (let i = 0; i <= 50; i += 2) graph.push([i, e / (1 + Math.exp(-(i - v) / 2)) + slope * Math.max(0, i - v)]); values = [['Titrant volume', result + ' mL'], ['Potential', e.toFixed(0) + ' mV'], ['Endpoint slope', slope.toFixed(1) + ' mV/mL']]; explain = 'The equivalence point is located from the steepest potential change.'; }
    else if (kind === 'brass') { const mass = n(p, 'sampleMass', 1), v = n(p, 'edtaVolume', 0), m = n(p, 'edtaMolarity', 0); value = clip(v * m * 6.35 / Math.max(mass, .01) * 10); result = value.toFixed(1); unit = '% copper'; text = '%Cu = EDTA titre × molarity × factor / mass'; given = v + ' mL, ' + m + ' M, ' + mass + ' g'; calc = result; values = [['Brass mass', mass.toFixed(2) + ' g'], ['EDTA titre', v.toFixed(1) + ' mL'], ['Copper percentage', result + '%']]; explain = 'EDTA complexes Cu²⁺; the titre is converted to percentage copper.'; }
    else if (kind === 'viscometer') { const t = n(p, 'flowTime', 1), tw = n(p, 'waterTime', 1), rho = n(p, 'density', 1); value = t / tw * rho; result = value.toFixed(3); unit = 'relative viscosity'; text = 'η/ηwater = (t/twater)(ρ/ρwater)'; given = t + ' s / ' + tw + ' s × ' + rho; calc = result; values = [['Sample time', t.toFixed(0) + ' s'], ['Water time', tw.toFixed(0) + ' s'], ['Relative viscosity', result]]; explain = 'Capillary flow time and density ratio determine relative viscosity.'; }
    else if (kind === 'chloride') { const v = n(p, 'silverNitrate', 0), m = n(p, 'molarity', 0), sv = n(p, 'sampleVolume', 1); value = v * m * 35450 / sv; result = value.toFixed(1); unit = 'mg/L chloride'; text = 'Cl⁻ = VAgNO₃ × M × 35450 / Vsample'; given = v + ' mL, ' + m + ' M, ' + sv + ' mL'; calc = result; values = [['AgNO₃ titre', v.toFixed(1) + ' mL'], ['Endpoint', 'Ag₂CrO₄ brick-red'], ['Chloride', result + ' mg/L']]; explain = 'Mohr titration precipitates chloride as AgCl; excess silver forms the chromate endpoint.'; }
    else if (kind === 'ph') { const av = n(p, 'acidVolume', 1), bv = n(p, 'baseVolume', 1), bm = n(p, 'baseMolarity', .1); value = bv * bm / av; result = value.toFixed(3); unit = 'mol/L HCl'; text = 'M_HCl = M_NaOH × VNaOH / VHCl'; given = bm + ' M × ' + bv + ' mL / ' + av + ' mL'; calc = result; graph = []; for (let i = 0; i <= 50; i += 2) { const delta = i - bv; graph.push([i, Math.max(1, Math.min(14, 7 + delta * 1.8 + Math.tanh(delta / 2) * 4))]); } values = [['NaOH endpoint', bv.toFixed(1) + ' mL'], ['Sample volume', av.toFixed(1) + ' mL'], ['HCl strength', result + ' M']]; explain = 'Neutralisation reaches the endpoint when moles of NaOH equal moles of HCl.'; }
    else { result = '0'; unit = 'units'; text = 'Measured result = model response'; values = [['Result', result]]; explain = 'Dedicated chemistry process model.'; }
    return { formula: formula('Calculated result', text, given, calc, result, unit), values: values, explain: explain, graph: graph };
  }

  function validate(kind, p) {
    const warnings = [];
    Object.keys(p || {}).forEach((key) => { if (Number.isFinite(Number(p[key])) && Number(p[key]) < 0 && !['current','potential','anode','cathode','metalA','metalB'].includes(key)) warnings.push(key + ' cannot be negative.'); });
    if (['edta','brass'].includes(kind) && n(p, 'sampleVolume', 1) <= 0) warnings.push('Sample volume must be greater than zero.');
    if (kind === 'edta' && n(p, 'edtaVolume', 0) < 0) warnings.push('EDTA titre cannot be negative.');
    if (kind === 'ph' && n(p, 'acidVolume', 0) <= 0) warnings.push('HCl sample volume must be greater than zero.');
    if (kind === 'viscometer' && n(p, 'waterTime', 0) <= 0) warnings.push('Water reference time must be greater than zero.');
    if (kind === 'alloy' && Math.abs(n(p,'copper',0) + n(p,'zinc',0) + n(p,'nickel',0) - 100) > 0.5) warnings.push('Alloy composition should total 100%.');
    if (kind === 'frp' && n(p,'fiber',0) > 80) warnings.push('Fibre fraction is outside the educational range.');
    if (kind === 'ro' && n(p,'pressure',0) <= 0) warnings.push('RO pressure must be above zero.');
    return warnings;
  }
  const calculateWaterHardness = (input) => calculate('hardness', input);
  const calculateEDTAHardness = (input) => calculate('edta', input);
  const calculateWaterTreatment = (kind, input) => calculate(kind, input);
  const calculateElectrochemicalCell = (input) => calculate('cell', input);
  const calculateCorrosion = (input) => calculate('corrosion', input);
  const calculateCalorificValue = (input) => calculate('calorific', input);
  const calculatePolymer = (kind, input) => calculate(kind, input);
  const calculateVirtualLab = (kind, input) => calculate(kind, input);
  window.ChemistryEngines = { calculate, validate, data: DATA, calculateWaterHardness, calculateEDTAHardness, calculateWaterTreatment, calculateElectrochemicalCell, calculateCorrosion, calculateCalorificValue, calculatePolymer, calculateVirtualLab };
})();
