import type { ISimulationCatalogItem } from './simulations.catalog.js';

const CHEM_SUBJECT_KEYWORDS = ['engineering chemistry', 'u21cy101', 'chemistry'];
function chemTemplate(id: string, unit: number, topic: string, title: string, description: string): ISimulationCatalogItem {
  return { id, domain: 'CHEMISTRY', category: 'engineering chemistry', title, description, suggestedUnits: [unit], smartboardPresetKey: id, defaultParams: { simulationType: 'engineering-chemistry', simulationSubtype: 'chemistry', defaultParameters: {}, visualizationMode: '', steps: [] }, tags: ['Engineering Chemistry', topic], subjectKeywords: CHEM_SUBJECT_KEYWORDS, unit, topic };
}

/** Engineering Chemistry (U21CY101), kept in syllabus order for teacher publishing and Smart Board launch. */
export const CHEM_SIMULATION_TEMPLATES: ISimulationCatalogItem[] = [
  chemTemplate("chem-hardness-water", 1, "Hardness of Water", "Hardness of Water Simulator", "Explore temporary, permanent and total hardness from Ca²⁺ and Mg²⁺ ions."),
  chemTemplate("chem-edta-hardness", 1, "EDTA Hardness Titration", "EDTA Hardness Titration Simulator", "Follow buffer, indicator, EDTA addition and endpoint to calculate hardness."),
  chemTemplate("chem-lime-soda", 1, "Lime-Soda Process", "Lime-Soda Water Softening Simulator", "Dose hard water with lime and soda ash and watch carbonate and hydroxide precipitation."),
  chemTemplate("chem-zeolite", 1, "Zeolite Process", "Zeolite Process Simulator", "Visualize Ca²⁺/Mg²⁺ exchange in a zeolite bed and its NaCl regeneration cycle."),
  chemTemplate("chem-ion-exchange", 1, "Ion Exchange", "Ion Exchange / Demineralization Simulator", "Trace cation exchange, anion exchange and H₂O formation."),
  chemTemplate("chem-reverse-osmosis", 1, "Reverse Osmosis", "Reverse Osmosis Simulator", "Adjust pressure, salt concentration and membrane efficiency across a semipermeable membrane."),
  chemTemplate("chem-municipal-treatment", 1, "Municipal Treatment", "Municipal Water Treatment Plant Simulator", "Step through coagulation, sedimentation, filtration and disinfection."),
  chemTemplate("chem-sedimentation", 1, "Sedimentation", "Sedimentation with Coagulant Simulator", "Change particles, settling time and coagulant dose to observe sludge formation."),
  chemTemplate("chem-sand-filtration", 1, "Sand Filtration", "Sand Filtration Simulator", "Animate suspended particles being trapped by sand and gravel layers."),
  chemTemplate("chem-chlorination", 1, "Disinfection", "Chlorination / Disinfection Simulator", "Adjust chlorine dose and contact time to reduce microorganisms."),
  chemTemplate("chem-uv-ozonation", 1, "Disinfection Comparison", "UV and Ozonation Comparison", "Compare chlorination, UV and ozonation by mechanism and residual effect."),
  chemTemplate("chem-electrodialysis", 1, "Electrodialysis", "Electrodialysis Simulator", "Animate cations and anions moving through alternating ion-selective membranes."),
  chemTemplate("chem-electrochemical-cell", 2, "Electrochemical Cells", "Electrochemical Cell Simulator", "Select electrodes and observe oxidation, reduction, electron flow and cell voltage."),
  chemTemplate("chem-electrochemical-series", 2, "Electrochemical Series", "Electrochemical Series Simulator", "Choose two metals and calculate E°cell, reaction direction and electron flow."),
  chemTemplate("chem-calomel-electrode", 2, "Reference Electrodes", "Calomel Electrode Simulator", "Explore the Hg | Hg₂Cl₂ | KCl reference electrode and its potential."),
  chemTemplate("chem-lead-acid", 2, "Batteries", "Lead-Acid Battery Simulator", "Switch between charging and discharging while tracking Pb, PbO₂, H₂SO₄ and ions."),
  chemTemplate("chem-lithium-ion", 2, "Batteries", "Lithium-Ion Battery Simulator", "Visualize Li⁺ movement between cathode and anode during charge and discharge."),
  chemTemplate("chem-fuel-cell", 2, "Fuel Cells", "Fuel Cell Simulator", "Follow hydrogen oxidation, electron flow and water formation in a fuel cell."),
  chemTemplate("chem-pem-fuel-cell", 2, "Fuel Cells", "Polymer Membrane Fuel Cell Simulator", "Separate proton movement through PEM from electron movement through the circuit."),
  chemTemplate("chem-sofc", 2, "Fuel Cells", "Solid Oxide Fuel Cell Simulator", "Adjust temperature and trace O²⁻ movement through the solid electrolyte."),
  chemTemplate("chem-solar-cell", 2, "Solar Energy", "Solar Cell Simulator", "Change light intensity, wavelength, temperature and load resistance to read V, I and power."),
  chemTemplate("chem-dssc", 2, "Solar Energy", "Dye-Sensitized Solar Cell Simulator", "Explore glass, dye, TiO₂, electrolyte and counter-electrode layers."),
  chemTemplate("chem-dry-corrosion", 3, "Corrosion Mechanisms", "Dry Corrosion Simulator", "Grow an oxide layer as a metal reacts with oxygen at adjustable temperature."),
  chemTemplate("chem-galvanic-corrosion", 3, "Corrosion Mechanisms", "Galvanic Corrosion Simulator", "Select two metals and identify the anode, cathode, electrolyte and metal loss."),
  chemTemplate("chem-differential-aeration", 3, "Corrosion Mechanisms", "Differential Aeration Corrosion", "Compare high-oxygen cathodic and low-oxygen anodic regions on a metal surface."),
  chemTemplate("chem-pitting", 3, "Localized Corrosion", "Pitting Corrosion Simulator", "Zoom from a surface defect to localized pit formation."),
  chemTemplate("chem-crevice", 3, "Localized Corrosion", "Crevice Corrosion Simulator", "Explore the low-oxygen electrochemical cell inside a joined crevice."),
  chemTemplate("chem-corrosion-factors", 3, "Corrosion Rate", "Factors Affecting Corrosion Simulator", "Change temperature, pH, oxygen, electrolyte, metal and surface condition."),
  chemTemplate("chem-sacrificial-anode", 3, "Corrosion Protection", "Sacrificial Anode Protection", "Watch zinc dissolve while an iron structure remains protected."),
  chemTemplate("chem-impressed-current", 3, "Corrosion Protection", "Impressed Current Cathodic Protection", "Adjust supplied current and protect a structure through an external anode."),
  chemTemplate("chem-electroplating", 3, "Surface Protection", "Electroplating Simulator", "Control current, time and concentration to calculate coating thickness."),
  chemTemplate("chem-nickel-plating", 3, "Surface Protection", "Nickel Plating Simulator", "Animate nickel deposition from an electrolyte onto a metal object."),
  chemTemplate("chem-alloy-composition", 3, "Materials", "Alloy Composition Simulator", "Compare brass, German silver and stainless-steel composition and properties."),
  chemTemplate("chem-heat-treatment", 3, "Materials", "Heat Treatment Simulator", "Compare heating, soaking and cooling schedules and their resulting properties."),
  chemTemplate("chem-proximate-analysis", 4, "Coal Analysis", "Proximate Analysis of Coal Simulator", "Determine moisture, volatile matter, ash and fixed carbon step by step."),
  chemTemplate("chem-coal-analysis", 4, "Coal Analysis", "Coal Analysis Simulator", "Change sample mass and measurements to calculate coal composition automatically."),
  chemTemplate("chem-bergius", 4, "Synthetic Fuels", "Bergius Process Simulator", "Follow coal hydrogenation at high pressure and temperature to synthetic petrol."),
  chemTemplate("chem-octane", 4, "Fuel Quality", "Octane Number Simulator", "Mix iso-octane and n-heptane references to calculate octane number."),
  chemTemplate("chem-cetane", 4, "Fuel Quality", "Cetane Number Simulator", "Compare diesel ignition delay and cetane characteristics."),
  chemTemplate("chem-knocking", 4, "Engine Combustion", "Knocking in Engines Simulator", "Compare smooth flame propagation with uncontrolled combustion and pressure waves."),
  chemTemplate("chem-antiknock", 4, "Engine Combustion", "Anti-Knocking Agent Simulator", "Compare low-octane fuel, high-octane fuel and anti-knocking treatment."),
  chemTemplate("chem-cng-lpg", 4, "Alternative Fuels", "CNG vs LPG Simulator", "Compare state, composition, storage, applications and combustion of CNG and LPG."),
  chemTemplate("chem-calorific-value", 4, "Calorimetry", "Calorific Value Simulator", "Vary fuel mass and heat released to calculate higher and lower calorific values."),
  chemTemplate("chem-bomb-calorimeter", 4, "Calorimetry", "Bomb Calorimeter Simulator", "Run the fuel sample, bomb, water-bath temperature rise and calorific-value workflow."),
  chemTemplate("chem-orsat", 4, "Flue Gas Analysis", "Flue Gas Analysis — Orsat Method", "Absorb CO₂, O₂ and CO sequentially and read remaining gas composition."),
  chemTemplate("chem-three-way-catalyst", 4, "Emission Control", "Three-Way Catalytic Converter", "Convert CO, hydrocarbons and NOx into less harmful exhaust products."),
  chemTemplate("chem-scr-nox", 4, "Emission Control", "Selective Catalytic Reduction of NOx", "Adjust NOx, reducing agent and temperature to produce N₂ and H₂O."),
  chemTemplate("chem-polymerization", 5, "Polymer Science", "Polymerization Simulator", "Increase monomers and watch a polymer chain grow."),
  chemTemplate("chem-degree-polymerization", 5, "Polymer Science", "Degree of Polymerization Simulator", "Calculate chain length from polymer and monomer molecular masses."),
  chemTemplate("chem-classification", 5, "Polymer Science", "Polymer Classification Simulator", "Explore thermoplastics, thermosets, elastomers and conducting polymers."),
  chemTemplate("chem-thermoplastic-thermoset", 5, "Polymer Behaviour", "Thermoplastic vs Thermosetting Simulator", "Compare softening and permanent cross-linking under heat."),
  chemTemplate("chem-glass-transition", 5, "Polymer Behaviour", "Glass Transition Temperature Simulator", "Move temperature across Tg and observe glassy-to-rubbery mobility."),
  chemTemplate("chem-abs", 5, "Engineering Polymers", "ABS Polymer Simulator", "Combine acrylonitrile, butadiene and styrene to explore ABS properties."),
  chemTemplate("chem-pvc", 5, "Engineering Polymers", "PVC Simulator", "Build PVC chains and connect structure with applications."),
  chemTemplate("chem-ptfe", 5, "Engineering Polymers", "PTFE Simulator", "Polymerize tetrafluoroethylene and explore low friction and chemical resistance."),
  chemTemplate("chem-bakelite", 5, "Engineering Polymers", "Bakelite Simulator", "Visualize thermosetting polymer formation and cross-linking."),
  chemTemplate("chem-injection-moulding", 5, "Processing", "Injection Moulding Simulator", "Heat pellets, inject the melt into a mould, cool and release the product."),
  chemTemplate("chem-extrusion", 5, "Processing", "Extrusion Moulding Simulator", "Adjust screw speed and temperature through heater, screw and die stages."),
  chemTemplate("chem-compression-moulding", 5, "Processing", "Compression Moulding Simulator", "Apply pressure and heat, then cool a polymer inside a mould."),
  chemTemplate("chem-conducting-polymer", 5, "Functional Polymers", "Conducting Polymer Simulator", "Compare polypyrrole, polyacetylene and polyaniline conductivity."),
  chemTemplate("chem-frp", 5, "Composite Materials", "Composite / FRP Simulator", "Change fibre fraction and orientation to explore conceptual FRP properties."),
  chemTemplate("chem-lab-edta", 6, "Virtual Laboratory", "Virtual Lab — EDTA Hardness", "Perform a virtual burette titration for total hardness."),
  chemTemplate("chem-lab-potentiometric", 6, "Virtual Laboratory", "Virtual Lab — Potentiometric Titration", "Add titrant and read the potential-versus-volume curve."),
  chemTemplate("chem-lab-brass", 6, "Virtual Laboratory", "Virtual Lab — Copper in Brass by EDTA", "Analyse a brass sample and calculate percentage copper."),
  chemTemplate("chem-lab-proximate", 6, "Virtual Laboratory", "Virtual Lab — Proximate Analysis", "Run the moisture, volatile matter, ash and fixed-carbon experiment."),
  chemTemplate("chem-lab-viscometer", 6, "Virtual Laboratory", "Virtual Lab — Ostwald Viscometer", "Relate flow time to viscosity, molecular weight and degree of polymerization."),
  chemTemplate("chem-lab-chloride", 6, "Virtual Laboratory", "Virtual Lab — Chloride Estimation", "Perform the titration procedure and calculate chloride concentration."),
  chemTemplate("chem-lab-ph", 6, "Virtual Laboratory", "Virtual Lab — pH Metric HCl Strength", "Measure HCl strength and follow the live pH-versus-volume curve."),
];
