import type { ISimulationDefinition } from './types';

const CHEM_SUBJECT_KEYWORDS = ['engineering chemistry', 'u21cy101', 'chemistry'];

function chemBoardSimulation(id: string, unit: number, unitTitle: string, subtype: string, topic: string, title: string, icon: string, shortDescription: string): ISimulationDefinition {
  return {
    id, boardEngine: 'chem', simulationSubtype: subtype, unit, unitTitle, topic, subjectKeywords: CHEM_SUBJECT_KEYWORDS,
    title, domain: 'CHEMISTRY', category: 'engineering chemistry', icon, shortDescription,
    detailedDescription: shortDescription + ' Interactive and step by step, with formulas, measurements and explanations — opens inside the Smart Board.',
    learningObjectives: ['Explain ' + topic + ' step by step', 'Relate the model to the measured result and explain how each parameter changes it'],
    suggestedUnits: [unit], smartboardPresetKey: id, tags: ['Engineering Chemistry', unitTitle, topic], parameters: [], metrics: [],
    engine: { createInitialState: () => ({}), update: (state) => state, render: (ctx, width, height) => { ctx.fillStyle = '#fffaf0'; ctx.fillRect(0, 0, width, height); } },
  };
}

/** Engineering Chemistry (U21CY101) — ordered Units I–V and Virtual Laboratory simulations. */
export const CHEMISTRY_BOARD_SIMULATIONS: ISimulationDefinition[] = [
  chemBoardSimulation("chem-hardness-water", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Hardness of Water", "Hardness of Water Simulator", "💧", "Explore temporary, permanent and total hardness from Ca²⁺ and Mg²⁺ ions."),
  chemBoardSimulation("chem-edta-hardness", 1, "Characteristics of Water and Its Treatment", "water-treatment", "EDTA Hardness Titration", "EDTA Hardness Titration Simulator", "🧪", "Follow buffer, indicator, EDTA addition and endpoint to calculate hardness."),
  chemBoardSimulation("chem-lime-soda", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Lime-Soda Process", "Lime-Soda Water Softening Simulator", "⚗️", "Dose hard water with lime and soda ash and watch carbonate and hydroxide precipitation."),
  chemBoardSimulation("chem-zeolite", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Zeolite Process", "Zeolite Process Simulator", "🪨", "Visualize Ca²⁺/Mg²⁺ exchange in a zeolite bed and its NaCl regeneration cycle."),
  chemBoardSimulation("chem-ion-exchange", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Ion Exchange", "Ion Exchange / Demineralization Simulator", "🔁", "Trace cation exchange, anion exchange and H₂O formation."),
  chemBoardSimulation("chem-reverse-osmosis", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Reverse Osmosis", "Reverse Osmosis Simulator", "🧫", "Adjust pressure, salt concentration and membrane efficiency across a semipermeable membrane."),
  chemBoardSimulation("chem-municipal-treatment", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Municipal Treatment", "Municipal Water Treatment Plant Simulator", "🏭", "Step through coagulation, sedimentation, filtration and disinfection."),
  chemBoardSimulation("chem-sedimentation", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Sedimentation", "Sedimentation with Coagulant Simulator", "⬇️", "Change particles, settling time and coagulant dose to observe sludge formation."),
  chemBoardSimulation("chem-sand-filtration", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Sand Filtration", "Sand Filtration Simulator", "🪨", "Animate suspended particles being trapped by sand and gravel layers."),
  chemBoardSimulation("chem-chlorination", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Disinfection", "Chlorination / Disinfection Simulator", "🧴", "Adjust chlorine dose and contact time to reduce microorganisms."),
  chemBoardSimulation("chem-uv-ozonation", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Disinfection Comparison", "UV and Ozonation Comparison", "☀️", "Compare chlorination, UV and ozonation by mechanism and residual effect."),
  chemBoardSimulation("chem-electrodialysis", 1, "Characteristics of Water and Its Treatment", "water-treatment", "Electrodialysis", "Electrodialysis Simulator", "⚡", "Animate cations and anions moving through alternating ion-selective membranes."),
  chemBoardSimulation("chem-electrochemical-cell", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Electrochemical Cells", "Electrochemical Cell Simulator", "🔋", "Select electrodes and observe oxidation, reduction, electron flow and cell voltage."),
  chemBoardSimulation("chem-electrochemical-series", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Electrochemical Series", "Electrochemical Series Simulator", "📋", "Choose two metals and calculate E°cell, reaction direction and electron flow."),
  chemBoardSimulation("chem-calomel-electrode", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Reference Electrodes", "Calomel Electrode Simulator", "⚙️", "Explore the Hg | Hg₂Cl₂ | KCl reference electrode and its potential."),
  chemBoardSimulation("chem-lead-acid", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Batteries", "Lead-Acid Battery Simulator", "🔋", "Switch between charging and discharging while tracking Pb, PbO₂, H₂SO₄ and ions."),
  chemBoardSimulation("chem-lithium-ion", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Batteries", "Lithium-Ion Battery Simulator", "🔋", "Visualize Li⁺ movement between cathode and anode during charge and discharge."),
  chemBoardSimulation("chem-fuel-cell", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Fuel Cells", "Fuel Cell Simulator", "⛽", "Follow hydrogen oxidation, electron flow and water formation in a fuel cell."),
  chemBoardSimulation("chem-pem-fuel-cell", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Fuel Cells", "Polymer Membrane Fuel Cell Simulator", "🧬", "Separate proton movement through PEM from electron movement through the circuit."),
  chemBoardSimulation("chem-sofc", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Fuel Cells", "Solid Oxide Fuel Cell Simulator", "🔥", "Adjust temperature and trace O²⁻ movement through the solid electrolyte."),
  chemBoardSimulation("chem-solar-cell", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Solar Energy", "Solar Cell Simulator", "☀️", "Change light intensity, wavelength, temperature and load resistance to read V, I and power."),
  chemBoardSimulation("chem-dssc", 2, "Electrochemistry and Energy Storage Systems", "electrochemistry", "Solar Energy", "Dye-Sensitized Solar Cell Simulator", "🌈", "Explore glass, dye, TiO₂, electrolyte and counter-electrode layers."),
  chemBoardSimulation("chem-dry-corrosion", 3, "Corrosion and Its Control", "corrosion", "Corrosion Mechanisms", "Dry Corrosion Simulator", "🧱", "Grow an oxide layer as a metal reacts with oxygen at adjustable temperature."),
  chemBoardSimulation("chem-galvanic-corrosion", 3, "Corrosion and Its Control", "corrosion", "Corrosion Mechanisms", "Galvanic Corrosion Simulator", "🔩", "Select two metals and identify the anode, cathode, electrolyte and metal loss."),
  chemBoardSimulation("chem-differential-aeration", 3, "Corrosion and Its Control", "corrosion", "Corrosion Mechanisms", "Differential Aeration Corrosion", "🌬️", "Compare high-oxygen cathodic and low-oxygen anodic regions on a metal surface."),
  chemBoardSimulation("chem-pitting", 3, "Corrosion and Its Control", "corrosion", "Localized Corrosion", "Pitting Corrosion Simulator", "🕳️", "Zoom from a surface defect to localized pit formation."),
  chemBoardSimulation("chem-crevice", 3, "Corrosion and Its Control", "corrosion", "Localized Corrosion", "Crevice Corrosion Simulator", "🔧", "Explore the low-oxygen electrochemical cell inside a joined crevice."),
  chemBoardSimulation("chem-corrosion-factors", 3, "Corrosion and Its Control", "corrosion", "Corrosion Rate", "Factors Affecting Corrosion Simulator", "📈", "Change temperature, pH, oxygen, electrolyte, metal and surface condition."),
  chemBoardSimulation("chem-sacrificial-anode", 3, "Corrosion and Its Control", "corrosion", "Corrosion Protection", "Sacrificial Anode Protection", "🛡️", "Watch zinc dissolve while an iron structure remains protected."),
  chemBoardSimulation("chem-impressed-current", 3, "Corrosion and Its Control", "corrosion", "Corrosion Protection", "Impressed Current Cathodic Protection", "🔌", "Adjust supplied current and protect a structure through an external anode."),
  chemBoardSimulation("chem-electroplating", 3, "Corrosion and Its Control", "corrosion", "Surface Protection", "Electroplating Simulator", "✨", "Control current, time and concentration to calculate coating thickness."),
  chemBoardSimulation("chem-nickel-plating", 3, "Corrosion and Its Control", "corrosion", "Surface Protection", "Nickel Plating Simulator", "🪙", "Animate nickel deposition from an electrolyte onto a metal object."),
  chemBoardSimulation("chem-alloy-composition", 3, "Corrosion and Its Control", "corrosion", "Materials", "Alloy Composition Simulator", "🧩", "Compare brass, German silver and stainless-steel composition and properties."),
  chemBoardSimulation("chem-heat-treatment", 3, "Corrosion and Its Control", "corrosion", "Materials", "Heat Treatment Simulator", "🌡️", "Compare heating, soaking and cooling schedules and their resulting properties."),
  chemBoardSimulation("chem-proximate-analysis", 4, "Fuels and Combustion", "fuels-combustion", "Coal Analysis", "Proximate Analysis of Coal Simulator", "🪨", "Determine moisture, volatile matter, ash and fixed carbon step by step."),
  chemBoardSimulation("chem-coal-analysis", 4, "Fuels and Combustion", "fuels-combustion", "Coal Analysis", "Coal Analysis Simulator", "⚖️", "Change sample mass and measurements to calculate coal composition automatically."),
  chemBoardSimulation("chem-bergius", 4, "Fuels and Combustion", "fuels-combustion", "Synthetic Fuels", "Bergius Process Simulator", "🏭", "Follow coal hydrogenation at high pressure and temperature to synthetic petrol."),
  chemBoardSimulation("chem-octane", 4, "Fuels and Combustion", "fuels-combustion", "Fuel Quality", "Octane Number Simulator", "⛽", "Mix iso-octane and n-heptane references to calculate octane number."),
  chemBoardSimulation("chem-cetane", 4, "Fuels and Combustion", "fuels-combustion", "Fuel Quality", "Cetane Number Simulator", "🚛", "Compare diesel ignition delay and cetane characteristics."),
  chemBoardSimulation("chem-knocking", 4, "Fuels and Combustion", "fuels-combustion", "Engine Combustion", "Knocking in Engines Simulator", "💥", "Compare smooth flame propagation with uncontrolled combustion and pressure waves."),
  chemBoardSimulation("chem-antiknock", 4, "Fuels and Combustion", "fuels-combustion", "Engine Combustion", "Anti-Knocking Agent Simulator", "🧴", "Compare low-octane fuel, high-octane fuel and anti-knocking treatment."),
  chemBoardSimulation("chem-cng-lpg", 4, "Fuels and Combustion", "fuels-combustion", "Alternative Fuels", "CNG vs LPG Simulator", "🚌", "Compare state, composition, storage, applications and combustion of CNG and LPG."),
  chemBoardSimulation("chem-calorific-value", 4, "Fuels and Combustion", "fuels-combustion", "Calorimetry", "Calorific Value Simulator", "🔥", "Vary fuel mass and heat released to calculate higher and lower calorific values."),
  chemBoardSimulation("chem-bomb-calorimeter", 4, "Fuels and Combustion", "fuels-combustion", "Calorimetry", "Bomb Calorimeter Simulator", "🌡️", "Run the fuel sample, bomb, water-bath temperature rise and calorific-value workflow."),
  chemBoardSimulation("chem-orsat", 4, "Fuels and Combustion", "fuels-combustion", "Flue Gas Analysis", "Flue Gas Analysis — Orsat Method", "🧪", "Absorb CO₂, O₂ and CO sequentially and read remaining gas composition."),
  chemBoardSimulation("chem-three-way-catalyst", 4, "Fuels and Combustion", "fuels-combustion", "Emission Control", "Three-Way Catalytic Converter", "🚘", "Convert CO, hydrocarbons and NOx into less harmful exhaust products."),
  chemBoardSimulation("chem-scr-nox", 4, "Fuels and Combustion", "fuels-combustion", "Emission Control", "Selective Catalytic Reduction of NOx", "🌫️", "Adjust NOx, reducing agent and temperature to produce N₂ and H₂O."),
  chemBoardSimulation("chem-polymerization", 5, "Polymers", "polymers", "Polymer Science", "Polymerization Simulator", "🔗", "Increase monomers and watch a polymer chain grow."),
  chemBoardSimulation("chem-degree-polymerization", 5, "Polymers", "polymers", "Polymer Science", "Degree of Polymerization Simulator", "📏", "Calculate chain length from polymer and monomer molecular masses."),
  chemBoardSimulation("chem-classification", 5, "Polymers", "polymers", "Polymer Science", "Polymer Classification Simulator", "🗂️", "Explore thermoplastics, thermosets, elastomers and conducting polymers."),
  chemBoardSimulation("chem-thermoplastic-thermoset", 5, "Polymers", "polymers", "Polymer Behaviour", "Thermoplastic vs Thermosetting Simulator", "♨️", "Compare softening and permanent cross-linking under heat."),
  chemBoardSimulation("chem-glass-transition", 5, "Polymers", "polymers", "Polymer Behaviour", "Glass Transition Temperature Simulator", "🌡️", "Move temperature across Tg and observe glassy-to-rubbery mobility."),
  chemBoardSimulation("chem-abs", 5, "Polymers", "polymers", "Engineering Polymers", "ABS Polymer Simulator", "🧱", "Combine acrylonitrile, butadiene and styrene to explore ABS properties."),
  chemBoardSimulation("chem-pvc", 5, "Polymers", "polymers", "Engineering Polymers", "PVC Simulator", "🧵", "Build PVC chains and connect structure with applications."),
  chemBoardSimulation("chem-ptfe", 5, "Polymers", "polymers", "Engineering Polymers", "PTFE Simulator", "⚪", "Polymerize tetrafluoroethylene and explore low friction and chemical resistance."),
  chemBoardSimulation("chem-bakelite", 5, "Polymers", "polymers", "Engineering Polymers", "Bakelite Simulator", "🧩", "Visualize thermosetting polymer formation and cross-linking."),
  chemBoardSimulation("chem-injection-moulding", 5, "Polymers", "polymers", "Processing", "Injection Moulding Simulator", "🏗️", "Heat pellets, inject the melt into a mould, cool and release the product."),
  chemBoardSimulation("chem-extrusion", 5, "Polymers", "polymers", "Processing", "Extrusion Moulding Simulator", "➡️", "Adjust screw speed and temperature through heater, screw and die stages."),
  chemBoardSimulation("chem-compression-moulding", 5, "Polymers", "polymers", "Processing", "Compression Moulding Simulator", "🗜️", "Apply pressure and heat, then cool a polymer inside a mould."),
  chemBoardSimulation("chem-conducting-polymer", 5, "Polymers", "polymers", "Functional Polymers", "Conducting Polymer Simulator", "⚡", "Compare polypyrrole, polyacetylene and polyaniline conductivity."),
  chemBoardSimulation("chem-frp", 5, "Polymers", "polymers", "Composite Materials", "Composite / FRP Simulator", "🧵", "Change fibre fraction and orientation to explore conceptual FRP properties."),
  chemBoardSimulation("chem-lab-edta", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — EDTA Hardness", "🧪", "Perform a virtual burette titration for total hardness."),
  chemBoardSimulation("chem-lab-potentiometric", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — Potentiometric Titration", "📉", "Add titrant and read the potential-versus-volume curve."),
  chemBoardSimulation("chem-lab-brass", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — Copper in Brass by EDTA", "🪙", "Analyse a brass sample and calculate percentage copper."),
  chemBoardSimulation("chem-lab-proximate", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — Proximate Analysis", "🪨", "Run the moisture, volatile matter, ash and fixed-carbon experiment."),
  chemBoardSimulation("chem-lab-viscometer", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — Ostwald Viscometer", "⏱️", "Relate flow time to viscosity, molecular weight and degree of polymerization."),
  chemBoardSimulation("chem-lab-chloride", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — Chloride Estimation", "🧴", "Perform the titration procedure and calculate chloride concentration."),
  chemBoardSimulation("chem-lab-ph", 6, "Virtual Laboratory", "virtual-lab", "Virtual Laboratory", "Virtual Lab — pH Metric HCl Strength", "🧪", "Measure HCl strength and follow the live pH-versus-volume curve."),
];
